export const URL = {
  base: import.meta.env.VITE_API_BASE_URL,
  globalSearch: "global-search/",
  loginUser: "accounts/login/",
  logoutUser: "accounts/logout/",
  refreshToken: "token/refresh/",
  groupCompany: "group-company-master/",
  callMode: "callmode/",
  termsOfShipment: "terms_of_shipment_master/",
  company: "company-master/",
  portMaster: "port-master/",
  containerType: "container_type_master/",
  callEntry: "call-entry/",
  profiling: "customer-profiling/",
  participants: "participants/",
  customer: "customer_master/customer-master/",
  allCustomers: "customer_master/conditional-list/",
  customerFilter: "filter/customer_master/customer-master/",
  transporter: "customer_master/customer-master/transporter/",
  consignee: "customer_master/customer-master/consignee/",
  agent: "customer_master/customer-master/agent/",
  /** Agent + Coloader search for Origin Agent fields (same response shape as agent search). */
  customerByTypes: "customer_master/customer-master/by-types/",
  supplierByType: "customer_master/customer-master/by-type/Supplier/",
  shipper: "customer_master/customer-master/shipper/",
  shipmentParty: "shipment-party/",
  forwarder: "customer_master/customer-master/forwarder/",
  cha: "customer_master/customer-master/cha/",
  followUpAction: "followup-master/",
  customerAddressMapping: "customer_address_mapping/",
  frequency: "frequency-master/",
  customerType: "customertype-master/",
  branchMaster: "branch-master/",
  serviceMaster: "service-master/",
  nearbyCustomers: "potential/nearbycustomer/",
  enquiry: "enquiry/",
  currencyMaster: "currency-master/",
  quotation: "quotation/",
  user: "user_master/",
  userByCoordinator: "user_master/by-coordinator/",
  coordinatorAssigned: "coordinator-access-mapping/coordinator-assigned/",
  customerRelationshipMapping: "customer-relationship-mapping/",
  customerRelationshipMappingByCustomer:
    "customer-relationship-mapping/by-customer/",
  customerRelationshipMappingBulkUpdate:
    "customer-relationship-mapping/bulk-update/",
  // tariff: "tariff/"
  carrier: "carrier-master/",
  freight: "freight/",
  origin: "origin/",
  destination: "destination/",
  asPerTariff: "quotation/as-per-tariff/",
  chatbot: "chatbot/",
  enquiryWithoutQuote: "enquiry/enquiries-without-quotation/",
  jobProfit: "job-profit/",
  reportsGenerate: "reports/generate/",
  localOutstanding: "local-outstanding/",
  getcharges: "comprehensive/",
  enquiryFilter: "enquiry/filter_enquiries/",
  rateRequest: "rate-request/",
  rateRequestSendEmail: "rate-request/send_service_email/",
  quotationApproval: "quotation/Approval/",
  quotationFilter: "quotation/filter_quotations/",
  accountsSalespersons: "accounts/salespersons/",
  quotationFilterApproval: "quotation/filter_quotations_approval/",
  quotationFilterGained: "quotation/filter-gained/",
  filter_call_entries: "call-entry/filter_call_entries/",
  filter_freight: "filter/freight/",
  filter_origin: "filter/origin/",
  filter_destination: "filter/destination/",
  enquiryPreviewExcel: "enquiry/preview-excel-data/",
  enquiryDownloadExcel: "enquiry/download-excel/",
  customerData: "call-entry/customer-data/",
  country: "country/",
  state: "state/",
  tdsSectionMaster: "tds_section_master/",
  tdsRateMaster: "tds_rate_master/",
  city: "city/",
  carrierComparison: "carrier-comparison/",
  exportShipment: "export-shipment/",
  exportShipmentFilter: "export-shipment/filter/",
  importShipment: "import-shipment/",
  importShipmentFilter: "import-shipment/filter/",
  customerServiceShipment: "customer-service-shipment/",
  customerServiceShipmentFilter: "customer-service-shipment/filter/",
  uploadDocument: "customer-service-shipment/upload-document/",
  eventMaster: "event-master/",
  eventMasterFilter: "filters_event_master/",
  triggerMaster: "trigger-master/filter/",
  booking: "booking/",
  bookingFilter: "booking/filter/",
  salespersons: "accounts/salespersons/",
  userBranchMapping: "user-branch-mapping/",
  getChargeswithoutEnquiry: "search-traiff/",
  potentialCustomers: "potential/filter/",
  userPotentialMaster: "user-potential-master/",
  potentialCustomerTemplate: "potential/download-template/",
  potentialCustomerBulkUpload: "potential/bulk_upload/",
  quotatoionPublicGetData: "quotation/get_quotation_details/",
  pipeline: "pipeline/",
  pipelineFilter: "pipeline/filter/",
  unitMasterFilter: "unit-master/filter/",
  daybookGet: "day-book-master/",
  daybook: "filter/day-book-master/",
  quotationDefaultChargesFilter: "quotation-default-charges/filter/",
  conditionalNotes: "conditions/conditional-notes/",
  quotationChargeHistory: "quotation/charge-history/",
  importJob: "job-create/",
  importJobFilter: "filter/job-create/",
  filterJobCreate: "filter/job-create/",
  jobCreate: "job-create/",
  quotationSendEmail: "quotation/send-email/",
  accountsSendEmail: "accounts/send-email/",
  leadFilter: "lead/lead-filter/",
  lead: "lead/",
  chargeMaster: "charge-master/",
  chargeMasterFilter: "filter/charge-master/",
  tdsSectionMasterFilter: "filter/tds_section_master/",
  tdsRateSectionMasterFilter: "filter/tds_rate_master/",
  cfsMaster: "cfs-master/",
  cfsMasterFilter: "filter/cfs-master/",
  networkMaster: "network-master/",
  chartOfAccounts: "chart-of-accounts/",
  chartOfAccountsFilter: "filter/chart-of-accounts/",
  glChargeMapping: "gl-charge-mapping/",
  glChargeMappingFilter: "filter/gl-charge-mapping/",
  gstChargeMapping: "gst-charge-mapping/",
  gstChargeMappingFilter: "filter/gst-charge-mapping/",
  gstChargeMappingGetEffectiveSac: "gst-charge-mapping/get-effective-sac/",
  gstRateMasterFilter: "filter/gst-rate-master/",
  gstSacMaster: "gst-sac-master/",
  gstSacMasterFilter: "filter/gst-sac-master/",
  invoice: "invoice/",
  invoiceFilter: "filter/invoice/",
  invoiceCalculateGstBreakup: "invoice/calculate-gst-breakup/",
  tdsCalculation: "tds_calculation/",
  invoiceReversableData: "invoice/reversable-data/",
  reverseInvoice: "reverse-invoice/",
  filterInvoice: "filter/invoice/",
  receiptFilter: "filter/receipt/",
  reverseReceiptFilter: "filter/reverse-receipt/",
  receipt: "receipt/",
  reverseReceipt: "reverse-receipt/",
  paymentFilter: "filter/payment/",
  payment: "payment/",
  reversePaymentFilter: "filter/reverse-payment/",
  reversePayment: "reverse-payment/",
  supplierInvoiceFilter: "filter/supplier-invoice/",
  supplierInvoice: "supplier-invoice/",
  reverseSupplierInvoiceFilter: "filter/reverse-supplier-invoice/",
  reverseSupplierInvoice: "reverse-supplier-invoice/",
  invoiceCombined: "invoice/combined/",
  paymentRequest: "payment-request/",
  paymentRequestFilter: "filter/payment-request/",
  journalVoucher: "journal_voucher/",
  journalVoucherFilter: "filter/journal_voucher/",
  journalVoucherReversal: "reverse_voucher/",
  journalVoucherReversalFilter: "filter/reverse_voucher/",
  subledgerEnquiry: "filter/subledger_enquiry/",
  documentAllocation: "filter/document_allocation/",
  outstandingAllocations: "outstanding-details/allocations/",
  outstandingAllocationDocuments: "outstanding-details/allocation-documents/",

  // PAN / GST utilities
  panGstByPan: "pan-gst-master/get-by-pan/",

  // Ocean schedule lookup (vessel-saved)
  vesselSavedSchedules: "searates/schedules/vessel-saved/",
  jobLedger: "filter/job_ledger/",

  // EDI download for jobs
  edi: "edi/",

  // Dashboard APIs
  dashboard: {
    outstandingSummary: "local-outstanding/salesman-summary/",
    callEntry: "call-entry/",
    callEntryStatistics: "call-entry/statistics/",
    enquiryConversion: "enquiry/salesperson-statistics/",
    budgetSummary: "enquiry/budget-summary/",
    customerNotVisited:
      "customer_master/customer-master/customers-not-visited/",
    lostCustomers: "dashboard/new-customer-shipment/get_lost_customers/",
    newCustomerShipment: "dashboard/new-customer-shipment",
    pipelineReport: "pipeline/dashboard/",
    pipelineReportRegional: "pipeline/dashboard/regional/",
    pipelineReportProduct: "pipeline/dashboard/product/",
    expected: "expected/",
    booking: "customer-service-shipment/formatted-list/",
    gainedQuotationsWithoutBooking:
      "pipeline/gained-quotations-without-booking/",
    gainedBookingsPendingJobs: "pipeline/gained-bookings-pending-jobs/",
    jobsWithoutBLReleased: "pipeline/jobs-without-bl-released/",
  },
};
