import type { FinancePendingActivitiesData } from "./financePendingActivitiesTypes";

const BRANCH_ROWS = [
  {
    branchName: "Mumbai",
    branchVariant: "mum",
    subtitle: "HQ · 18 ops + 6 finance",
    invoiceCount: 14,
    invoiceAmountCr: 0.74,
    costCount: 22,
    costAmountCr: 0.26,
    distribution: [
      { category: "invoices" as const, flex: 74 },
      { category: "costs" as const, flex: 26 },
      { category: "vouchers" as const, flex: 18 },
      { category: "credit_notes" as const, flex: 6 },
    ],
    totalExposureCr: 1.24,
    owner: "A. Bhat",
  },
  {
    branchName: "Delhi",
    branchVariant: "del",
    subtitle: "12 ops + 3 finance",
    invoiceCount: 9,
    invoiceAmountCr: 0.42,
    costCount: 14,
    costAmountCr: 0.14,
    distribution: [
      { category: "invoices" as const, flex: 42 },
      { category: "costs" as const, flex: 14 },
      { category: "vouchers" as const, flex: 8 },
      { category: "credit_notes" as const, flex: 4 },
    ],
    totalExposureCr: 0.68,
    owner: "N. Khurana",
  },
  {
    branchName: "Bangalore",
    branchVariant: "blr",
    subtitle: "9 ops + 2 finance",
    invoiceCount: 7,
    invoiceAmountCr: 0.32,
    costCount: 11,
    costAmountCr: 0.09,
    distribution: [
      { category: "invoices" as const, flex: 32 },
      { category: "costs" as const, flex: 9 },
      { category: "vouchers" as const, flex: 6 },
      { category: "credit_notes" as const, flex: 2 },
    ],
    totalExposureCr: 0.49,
    owner: "S. Reddy",
  },
  {
    branchName: "Chennai",
    branchVariant: "maa",
    subtitle: "10 ops + 2 finance",
    watchLabel: "Watch",
    watchTone: "warn" as const,
    invoiceCount: 6,
    invoiceAmountCr: 0.28,
    costCount: 10,
    costAmountCr: 0.08,
    distribution: [
      { category: "invoices" as const, flex: 28 },
      { category: "costs" as const, flex: 8 },
      { category: "vouchers" as const, flex: 5 },
      { category: "credit_notes" as const, flex: 2 },
    ],
    totalExposureCr: 0.43,
    owner: "K. Iyer",
  },
  {
    branchName: "Ahmedabad",
    branchVariant: "amd",
    subtitle: "7 ops + 1 finance",
    watchLabel: "High",
    watchTone: "bad" as const,
    invoiceCount: 3,
    invoiceAmountCr: 0.06,
    costCount: 6,
    costAmountCr: 0.024,
    distribution: [
      { category: "invoices" as const, flex: 6 },
      { category: "costs" as const, flex: 2.4 },
      { category: "vouchers" as const, flex: 2 },
      { category: "credit_notes" as const, flex: 1.6 },
    ],
    totalExposureCr: 0.12,
    owner: "D. Shah",
  },
  {
    branchName: "Kolkata",
    branchVariant: "ccu",
    subtitle: "5 ops + 1 finance",
    watchLabel: "Behind",
    watchTone: "bad" as const,
    invoiceCount: 1,
    invoiceAmountCr: 0.02,
    costCount: 3,
    costAmountCr: 0.014,
    distribution: [
      { category: "invoices" as const, flex: 2 },
      { category: "costs" as const, flex: 1.4 },
      { category: "vouchers" as const, flex: 0.5 },
      { category: "credit_notes" as const, flex: 0 },
    ],
    totalExposureCr: 0.036,
    owner: "R. Das",
  },
];

const INVOICE_ITEMS = [
  {
    title: "Reliance Industries",
    subtitle: "Ocean FCL · JNPT → HAM · delivered 2 Apr",
    reference: "JOB-26-04188",
    amountCr: 0.142,
    ageDays: 21,
    branchCode: "MUM",
    branchVariant: "mum",
  },
  {
    title: "Tata Steel Ltd.",
    subtitle: "Ocean FCL · MUN → DXB · delivered 5 Apr",
    reference: "JOB-26-04172",
    amountCr: 0.128,
    ageDays: 18,
    branchCode: "MUM",
    branchVariant: "mum",
  },
  {
    title: "Maruti Suzuki India",
    subtitle: "Air · DEL → FRA · delivered 9 Apr",
    reference: "JOB-26-04165",
    amountCr: 0.096,
    ageDays: 14,
    branchCode: "DEL",
    branchVariant: "del",
  },
  {
    title: "Asian Paints Ltd.",
    subtitle: "Ocean LCL · MUN → JEB · delivered 11 Apr",
    reference: "JOB-26-04158",
    amountCr: 0.072,
    ageDays: 12,
    branchCode: "MUM",
    branchVariant: "mum",
  },
  {
    title: "Wipro Consumer Care",
    subtitle: "Air · BLR → LHR · delivered 12 Apr",
    reference: "JOB-26-04151",
    amountCr: 0.064,
    ageDays: 11,
    branchCode: "BLR",
    branchVariant: "blr",
  },
  {
    title: "Havells India",
    subtitle: "Ocean FCL · MUN → DUR · delivered 14 Apr",
    reference: "JOB-26-04142",
    amountCr: 0.058,
    ageDays: 9,
    branchCode: "DEL",
    branchVariant: "del",
  },
  {
    title: "Apollo Tyres",
    subtitle: "Customs · MAA · cleared 15 Apr",
    reference: "JOB-26-04138",
    amountCr: 0.052,
    ageDays: 7,
    branchCode: "MAA",
    branchVariant: "maa",
  },
  {
    title: "Dabur India",
    subtitle: "Air · DEL → LHR · delivered 16 Apr",
    reference: "JOB-26-04130",
    amountCr: 0.048,
    ageDays: 6,
    branchCode: "DEL",
    branchVariant: "del",
  },
];

const COST_ITEMS = [
  {
    title: "CMA CGM India",
    subtitle: "Ocean freight · JNPT → HAM · 2× FCL",
    reference: "BL-MAEU-2418",
    amountCr: 0.084,
    ageDays: 12,
    branchCode: "MUM",
    branchVariant: "mum",
  },
  {
    title: "Emirates SkyCargo",
    subtitle: "Air freight · DEL → FRA",
    reference: "AWB-176-4821",
    amountCr: 0.062,
    ageDays: 8,
    branchCode: "DEL",
    branchVariant: "del",
  },
  {
    title: "DP World Chennai",
    subtitle: "Terminal handling · MAA",
    reference: "THC-MAA-884",
    amountCr: 0.038,
    ageDays: 6,
    branchCode: "MAA",
    branchVariant: "maa",
  },
  {
    title: "Gati KWE",
    subtitle: "Road haulage · AMD corridor",
    reference: "GR-AMD-112",
    amountCr: 0.024,
    ageDays: 5,
    branchCode: "AMD",
    branchVariant: "amd",
  },
];

const VOUCHER_ITEMS = [
  {
    title: "Maersk India — vendor payment",
    subtitle: "PV-26-0418",
    reference: "PV-26-0418",
    amountCr: 0.126,
    ageDays: 9,
    branchCode: "MUM",
    branchVariant: "mum",
    typeTag: "Payment",
    statusNote: "approval pending — CFO",
  },
  {
    title: "FX revaluation Apr",
    subtitle: "JV-26-0420",
    reference: "JV-26-0420",
    amountCr: 0.084,
    ageDays: 5,
    branchCode: "BLR",
    branchVariant: "blr",
    typeTag: "Journal",
    statusNote: "₹/USD adjustment",
  },
  {
    title: "Terminal charges — MAA",
    subtitle: "PV-26-0402",
    reference: "PV-26-0402",
    amountCr: 0.062,
    ageDays: 3,
    branchCode: "MAA",
    branchVariant: "maa",
    typeTag: "Payment",
    statusNote: "review by Acct Head",
  },
  {
    title: "Petty cash replenishment",
    subtitle: "PV-26-0398",
    reference: "PV-26-0398",
    amountCr: 0.018,
    ageDays: 1,
    branchCode: "AMD",
    branchVariant: "amd",
    typeTag: "Payment",
  },
];

export const FINANCE_PENDING_ACTIVITIES_MOCK: FinancePendingActivitiesData = {
  meta: {
    title: "Pending Activities",
    subtitle:
      "Items blocking month-end close · 42 invoices to raise · 68 costs to book · 23 vouchers awaiting approval · 12 credit notes pending",
    asOfLabel: "Open as of today",
  },
  kpis: [
    {
      id: "invoices",
      label: "Invoices to Raise",
      subtitle: "Shipments delivered, invoice pending",
      amountCr: 1.84,
      count: 42,
      avgAgeDays: 14,
      highlightLabel: "Over 30d",
      highlightValue: 8,
      highlightTone: "bad",
    },
    {
      id: "costs",
      label: "Costs to Book",
      subtitle: "Vendor bills not posted to job",
      amountCr: 0.624,
      count: 68,
      avgAgeDays: 9,
      highlightLabel: "Pre-MEC",
      highlightValue: 22,
      highlightTone: "warn",
    },
    {
      id: "vouchers",
      label: "Vouchers Pending Approval",
      subtitle: "Payment + journal vouchers",
      amountCr: 0.386,
      count: 23,
      avgAgeDays: 3,
      highlightLabel: "Over 7d",
      highlightValue: 4,
      highlightTone: "bad",
    },
    {
      id: "credit_notes",
      label: "Credit Notes Pending",
      subtitle: "Awaiting approval / issuance",
      amountCr: 0.142,
      count: 12,
      avgAgeDays: 6,
      highlightLabel: "Disputes",
      highlightValue: 5,
      highlightTone: "warn",
    },
  ],
  byBranch: {
    rows: BRANCH_ROWS,
    total: {
      branchName: "All Branches",
      invoiceCount: 42,
      invoiceAmountCr: 1.84,
      costCount: 68,
      costAmountCr: 0.624,
      distribution: [],
      totalExposureCr: 2.99,
      owner: "",
    },
  },
  invoicesPanel: {
    id: "invoices",
    title: "Invoices to Raise",
    subtitle: "Top 8 by exposure · 42 total",
    totalCount: 42,
    filterTabs: [
      { value: "all", label: "All" },
      { value: "over_30", label: "> 30d" },
      { value: "pre_mec", label: "Pre-MEC" },
    ],
    items: INVOICE_ITEMS.map((item, i) => ({ ...item, id: `inv-${i}`, iconTone: "invoices" as const })),
    moreCount: 34,
    moreLabel: "invoices",
  },
  costsPanel: {
    id: "costs",
    title: "Costs to Book",
    subtitle: "Vendor bills awaiting job-cost entry · 68 total",
    totalCount: 68,
    items: COST_ITEMS.map((item, i) => ({ ...item, id: `cost-${i}`, iconTone: "costs" as const })),
    moreCount: 63,
    moreLabel: "entries",
  },
  vouchersPanel: {
    id: "vouchers",
    title: "Vouchers Awaiting Approval",
    subtitle: "Payment + journal · 23 total",
    totalCount: 23,
    items: VOUCHER_ITEMS.map((item, i) => ({ ...item, id: `vch-${i}`, iconTone: "vouchers" as const })),
    moreCount: 18,
    moreLabel: "vouchers",
  },
  filterOptions: {
    branches: [
      { value: "mum", label: "Mumbai" },
      { value: "del", label: "Delhi" },
      { value: "blr", label: "Bangalore" },
    ],
    owners: [
      { value: "a_bhat", label: "A. Bhat" },
      { value: "n_khurana", label: "N. Khurana" },
    ],
  },
};
