import type { CollectionTargetVsPerformanceData } from "./collectionTargetVsPerformanceTypes";

export const COLLECTION_TARGET_VS_PERFORMANCE_MOCK: CollectionTargetVsPerformanceData = {
  meta: {
    title: "Collection Target vs Performance",
    subtitle:
      "FY 25–26 YTD · ₹36.50 Cr collected of ₹39.20 Cr target · 93.1% achievement · DSO 47 days",
    periodLabel: "FY 25–26 YTD",
  },
  kpis: [
    {
      label: "Target YTD",
      value: 39.2,
      unit: "Cr",
      showCurrency: true,
      context: "Plan",
    },
    {
      label: "Collected YTD",
      value: 36.5,
      unit: "Cr",
      showCurrency: true,
      trendText: "−₹2.70 Cr",
      trendDirection: "down",
    },
    {
      label: "Achievement",
      value: 93.1,
      unit: "%",
      trendText: "+1.8pp MoM",
      trendDirection: "up",
    },
    {
      label: "DSO",
      value: 47,
      unit: "days",
      trendText: "+3 days",
      trendDirection: "down",
    },
    {
      label: "CEI",
      value: 86.4,
      unit: "%",
      trendText: "+2.1pp",
      trendDirection: "up",
    },
  ],
  thisMonth: {
    title: "This Month — Apr 2026",
    subtitle: "22 days into month · ₹2.84 Cr collected of ₹3.20 Cr target",
    gaugePct: 88.75,
    stats: [
      { label: "Collected", value: "₹2.84 Cr", detail: "220 receipts" },
      { label: "Remaining", value: "₹36 L", detail: "8 working days" },
      {
        label: "Run-rate / day",
        value: "₹12.9 L",
        detail: "Above ₹10.5 L need",
        detailTone: "up",
      },
      {
        label: "Forecast EOM",
        value: "₹3.27 Cr",
        detail: "▲ +₹7 L vs target",
        detailTone: "up",
      },
    ],
  },
  dailyCollection: {
    title: "Daily Collection · Apr 2026",
    subtitle: "Daily inflows vs daily run-rate need (₹10.5 L)",
    runRateNeed: 10.5,
    runRateLabel: "Need ₹10.5 L/day",
    points: [
      { day: 1, amount: 18.5 },
      { day: 2, amount: 12.0 },
      { day: 3, amount: 22.0 },
      { day: 4, amount: 0 },
      { day: 5, amount: 14.5 },
      { day: 6, amount: 0 },
      { day: 7, amount: 11.0 },
      { day: 8, amount: 23.5 },
      { day: 9, amount: 16.0 },
      { day: 10, amount: 19.0 },
      { day: 11, amount: 0 },
      { day: 12, amount: 0 },
      { day: 13, amount: 24.0 },
      { day: 14, amount: 10.5 },
      { day: 15, amount: 17.5 },
      { day: 16, amount: 21.0 },
      { day: 17, amount: 14.0 },
      { day: 18, amount: 0 },
      { day: 19, amount: 0 },
      { day: 20, amount: 25.0 },
      { day: 21, amount: 18.0 },
      { day: 22, amount: 12.5 },
    ],
  },
  branchPerformance: {
    rows: [
      {
        branchName: "HQ",
        branchCode: "MUM",
        branchVariant: "mum",
        subtitle: "12 collectors · ₹4.85 Cr book",
        target: 14.2,
        collected: 13.84,
        barCollectedWidthPct: 82,
        markerLeftPct: 84,
        barTone: "neutral",
        gap: -0.36,
        gapDisplay: "−₹36 L",
        gapDirection: "neg",
        achievementPct: 97.5,
      },
      {
        branchName: "Delhi",
        branchCode: "DEL",
        branchVariant: "del",
        subtitle: "8 collectors · ₹2.42 Cr book",
        target: 8.8,
        collected: 8.62,
        barCollectedWidthPct: 51,
        markerLeftPct: 52,
        barTone: "over",
        gap: -0.18,
        gapDisplay: "−₹18 L",
        gapDirection: "neg",
        achievementPct: 98.0,
      },
      {
        branchName: "Bangalore",
        branchCode: "BLR",
        branchVariant: "blr",
        subtitle: "6 collectors · ₹1.84 Cr book",
        target: 6.2,
        collected: 5.88,
        barCollectedWidthPct: 35,
        markerLeftPct: 37,
        barTone: "neutral",
        gap: -0.32,
        gapDisplay: "−₹32 L",
        gapDirection: "neg",
        achievementPct: 94.8,
      },
      {
        branchName: "Chennai",
        branchCode: "MAA",
        branchVariant: "maa",
        subtitle: "7 collectors · ₹2.18 Cr book",
        target: 5.6,
        collected: 4.86,
        barCollectedWidthPct: 29,
        markerLeftPct: 33,
        barTone: "under",
        gap: -0.74,
        gapDisplay: "−₹74 L",
        gapDirection: "neg",
        achievementPct: 86.8,
      },
      {
        branchName: "Ahmedabad",
        branchCode: "AMD",
        branchVariant: "amd",
        subtitle: "4 collectors · ₹98 L book",
        target: 2.8,
        collected: 2.34,
        barCollectedWidthPct: 14,
        markerLeftPct: 17,
        barTone: "under",
        gap: -0.46,
        gapDisplay: "−₹46 L",
        gapDirection: "neg",
        achievementPct: 83.6,
      },
      {
        branchName: "Kolkata",
        branchCode: "CCU",
        branchVariant: "ccu",
        subtitle: "3 collectors · ₹56 L book",
        exposureLabel: "High exposure",
        exposureTone: "bad",
        target: 1.6,
        collected: 0.96,
        barCollectedWidthPct: 6,
        markerLeftPct: 10,
        barTone: "under",
        gap: -0.64,
        gapDisplay: "−₹64 L",
        gapDirection: "neg",
        achievementPct: 60.0,
      },
    ],
    total: {
      branchName: "All Branches",
      target: 39.2,
      collected: 36.5,
      barCollectedWidthPct: 53,
      markerLeftPct: 57,
      barTone: "neutral",
      gap: -2.7,
      gapDisplay: "−₹2.70 Cr",
      gapDirection: "neg",
      achievementPct: 93.1,
    },
  },
};
