import type { FinanceOutstandingAgeingData } from "./financeOutstandingAgeingTypes";

const CUSTOMER_BRANCH_ROWS = [
  {
    primaryLabel: "Mumbai",
    branchVariant: "mum",
    showBranchChip: true,
    subtitle: "62 customers · DSO 42d · top: Reliance, Tata Steel",
    outstanding: 4.86,
    current: 3.78,
    days1_30: 0.64,
    days31_60: 0.28,
    days60Plus: 0.16,
    risk: "low" as const,
  },
  {
    primaryLabel: "Delhi",
    branchVariant: "del",
    showBranchChip: true,
    subtitle: "38 customers · DSO 45d · top: Dabur, Havells",
    outstanding: 2.42,
    current: 1.84,
    days1_30: 0.32,
    days31_60: 0.14,
    days60Plus: 0.12,
    risk: "low" as const,
  },
  {
    primaryLabel: "Bangalore",
    branchVariant: "blr",
    showBranchChip: true,
    subtitle: "28 customers · DSO 49d · top: Wipro, Infosys",
    outstanding: 1.84,
    current: 1.38,
    days1_30: 0.24,
    days31_60: 0.12,
    days60Plus: 0.1,
    risk: "medium" as const,
  },
  {
    primaryLabel: "Chennai",
    branchVariant: "maa",
    showBranchChip: true,
    subtitle: "32 customers · DSO 52d · top: Apollo, TVS",
    watchLabel: "Watch",
    watchTone: "warn" as const,
    outstanding: 2.18,
    current: 1.42,
    days1_30: 0.36,
    days31_60: 0.18,
    days60Plus: 0.22,
    highlight60Plus: true,
    risk: "medium" as const,
  },
  {
    primaryLabel: "Ahmedabad",
    branchVariant: "amd",
    showBranchChip: true,
    subtitle: "14 customers · DSO 58d · top: Adani, Torrent",
    watchLabel: "High",
    watchTone: "bad" as const,
    outstanding: 0.98,
    current: 0.52,
    days1_30: 0.18,
    days31_60: 0.12,
    days60Plus: 0.16,
    highlight60Plus: true,
    risk: "high" as const,
  },
  {
    primaryLabel: "Kolkata",
    branchVariant: "ccu",
    showBranchChip: true,
    subtitle: "10 customers · DSO 64d · top: ITC, CESC",
    watchLabel: "Hold",
    watchTone: "bad" as const,
    outstanding: 0.14,
    current: 0.06,
    days1_30: 0.02,
    days31_60: 0.02,
    days60Plus: 0.04,
    highlight60Plus: true,
    risk: "high" as const,
  },
];

const CUSTOMER_PARTY_ROWS = [
  {
    primaryLabel: "Reliance Industries",
    subtitle: "MUM · Credit ₹2.5 Cr · Net 45 · R. Sharma",
    outstanding: 1.42,
    current: 1.18,
    days1_30: 0.16,
    days31_60: 0.06,
    days60Plus: 0.02,
    risk: "low" as const,
  },
  {
    primaryLabel: "Tata Steel Ltd.",
    subtitle: "MUM · Credit ₹1.5 Cr · Net 30 · R. Sharma",
    outstanding: 0.98,
    current: 0.72,
    days1_30: 0.18,
    days31_60: 0.06,
    days60Plus: 0.02,
    risk: "low" as const,
  },
  {
    primaryLabel: "Maruti Suzuki India",
    subtitle: "DEL · Credit ₹1.2 Cr · Net 60 · P. Kapoor",
    outstanding: 0.84,
    current: 0.68,
    days1_30: 0.12,
    days31_60: 0.04,
    days60Plus: 0,
    risk: "low" as const,
  },
  {
    primaryLabel: "Asian Paints Ltd.",
    subtitle: "MUM · Credit ₹80 L · Net 45 · P. Kapoor",
    outstanding: 0.68,
    current: 0.48,
    days1_30: 0.14,
    days31_60: 0.04,
    days60Plus: 0.02,
    risk: "low" as const,
  },
  {
    primaryLabel: "Apollo Tyres",
    subtitle: "MAA · Credit ₹60 L · Net 60 · A. Menon",
    watchLabel: "Watch",
    watchTone: "warn" as const,
    outstanding: 0.62,
    current: 0.28,
    days1_30: 0.14,
    days31_60: 0.1,
    days60Plus: 0.1,
    highlight60Plus: true,
    risk: "high" as const,
  },
  {
    primaryLabel: "Adani Wilmar",
    subtitle: "AMD · Credit ₹75 L · Net 45 · D. Verma",
    outstanding: 0.54,
    current: 0.32,
    days1_30: 0.12,
    days31_60: 0.06,
    days60Plus: 0.04,
    risk: "medium" as const,
  },
  {
    primaryLabel: "Havells India",
    subtitle: "DEL · Credit ₹45 L · Net 45 · P. Kapoor",
    outstanding: 0.46,
    current: 0.34,
    days1_30: 0.08,
    days31_60: 0.02,
    days60Plus: 0.02,
    risk: "low" as const,
  },
  {
    primaryLabel: "Wipro Consumer Care",
    subtitle: "BLR · Credit ₹50 L · Net 45 · A. Menon",
    outstanding: 0.42,
    current: 0.26,
    days1_30: 0.1,
    days31_60: 0.04,
    days60Plus: 0.02,
    risk: "low" as const,
  },
  {
    primaryLabel: "Torrent Power",
    subtitle: "AMD · Credit ₹30 L · Net 30 · D. Verma",
    watchLabel: "Stop",
    watchTone: "bad" as const,
    outstanding: 0.32,
    current: 0,
    days1_30: 0.04,
    days31_60: 0.06,
    days60Plus: 0.22,
    highlight60Plus: true,
    risk: "high" as const,
  },
  {
    primaryLabel: "TVS Motor Co.",
    subtitle: "MAA · Credit ₹40 L · Net 30 · S. Naidu",
    outstanding: 0.28,
    current: 0.18,
    days1_30: 0.06,
    days31_60: 0.02,
    days60Plus: 0.02,
    risk: "low" as const,
  },
];

const AGENT_BRANCH_ROWS = [
  {
    primaryLabel: "Mumbai",
    branchVariant: "mum",
    showBranchChip: true,
    subtitle: "14 agents · top: Kuehne+Nagel, DB Schenker, MSC",
    outstanding: 1.84,
    current: 1.42,
    days1_30: 0.26,
    days31_60: 0.1,
    days60Plus: 0.06,
    risk: "low" as const,
  },
  {
    primaryLabel: "Delhi",
    branchVariant: "del",
    showBranchChip: true,
    subtitle: "10 agents · top: DHL, Expeditors, Yusen",
    outstanding: 1.12,
    current: 0.84,
    days1_30: 0.16,
    days31_60: 0.06,
    days60Plus: 0.06,
    risk: "low" as const,
  },
  {
    primaryLabel: "Bangalore",
    branchVariant: "blr",
    showBranchChip: true,
    subtitle: "6 agents · top: Bollore, Hellmann",
    outstanding: 0.72,
    current: 0.54,
    days1_30: 0.1,
    days31_60: 0.04,
    days60Plus: 0.04,
    risk: "low" as const,
  },
  {
    primaryLabel: "Chennai",
    branchVariant: "maa",
    showBranchChip: true,
    subtitle: "5 agents · top: ONE, Hapag-Lloyd",
    outstanding: 0.68,
    current: 0.42,
    days1_30: 0.14,
    days31_60: 0.06,
    days60Plus: 0.06,
    risk: "medium" as const,
  },
  {
    primaryLabel: "Ahmedabad",
    branchVariant: "amd",
    showBranchChip: true,
    subtitle: "2 agents · top: Cosco",
    watchLabel: "Dispute",
    watchTone: "warn" as const,
    outstanding: 0.38,
    current: 0.18,
    days1_30: 0.1,
    days31_60: 0.06,
    days60Plus: 0.04,
    highlight60Plus: true,
    risk: "high" as const,
  },
  {
    primaryLabel: "Kolkata",
    branchVariant: "ccu",
    showBranchChip: true,
    subtitle: "1 agent · CMA CGM",
    outstanding: 0.12,
    current: 0.06,
    days1_30: 0.02,
    days31_60: 0.02,
    days60Plus: 0.02,
    highlight60Plus: true,
    risk: "high" as const,
  },
];

const CUSTOMER_BUCKETS = [
  { id: "current", label: "Current", amountCr: 8.84, pct: 71.2, invoiceCount: 412 },
  { id: "days_1_30", label: "1–30 days", amountCr: 1.82, pct: 14.6, invoiceCount: 96 },
  { id: "days_31_60", label: "31–60 days", amountCr: 0.84, pct: 6.8, invoiceCount: 48 },
  { id: "days_61_90", label: "61–90 days", amountCr: 0.52, pct: 4.2, invoiceCount: 32 },
  {
    id: "days_90_plus",
    label: "90+ days",
    amountCr: 0.4,
    pct: 3.2,
    invoiceCount: 24,
    footnote: "High risk",
    footnoteTone: "bad" as const,
  },
];

const AGENT_BUCKETS = [
  { id: "current", label: "Current", amountCr: 3.42, pct: 70.4, invoiceCount: 218 },
  { id: "days_1_30", label: "1–30 days", amountCr: 0.78, pct: 16.0, invoiceCount: 54 },
  { id: "days_31_60", label: "31–60 days", amountCr: 0.38, pct: 7.8, invoiceCount: 26 },
  { id: "days_61_90", label: "61–90 days", amountCr: 0.18, pct: 3.7, invoiceCount: 12 },
  {
    id: "days_90_plus",
    label: "90+ days",
    amountCr: 0.1,
    pct: 2.1,
    invoiceCount: 8,
    footnote: "Dispute",
    footnoteTone: "bad" as const,
  },
];

function totalRow(
  label: string,
  rows: typeof CUSTOMER_BRANCH_ROWS,
): (typeof CUSTOMER_BRANCH_ROWS)[0] & { primaryLabel: string } {
  const sum = (key: keyof (typeof CUSTOMER_BRANCH_ROWS)[0]) =>
    rows.reduce((acc, r) => acc + (typeof r[key] === "number" ? (r[key] as number) : 0), 0);
  return {
    primaryLabel: label,
    subtitle: "",
    showBranchChip: false,
    outstanding: sum("outstanding"),
    current: sum("current"),
    days1_30: sum("days1_30"),
    days31_60: sum("days31_60"),
    days60Plus: sum("days60Plus"),
    risk: "low",
  };
}

export const FINANCE_OUTSTANDING_AGEING_MOCK: FinanceOutstandingAgeingData = {
  meta: {
    title: "Outstanding & Ageing",
    subtitle:
      "Total receivables ₹12.42 Cr · payables ₹4.86 Cr · 612 open invoices · 184 customers · 38 agents",
    asOfLabel: "As of 23 Apr 2026",
  },
  customer: {
    tabLabel: "Customer Outstanding",
    amountCr: 12.42,
    ageingBuckets: CUSTOMER_BUCKETS,
    byBranch: {
      rows: CUSTOMER_BRANCH_ROWS,
      total: {
        ...totalRow("Total Receivables", CUSTOMER_BRANCH_ROWS),
        risk: "low",
      },
    },
    byParty: {
      rows: CUSTOMER_PARTY_ROWS,
      total: {
        ...totalRow("Top customers", CUSTOMER_PARTY_ROWS),
        risk: "low",
      },
      moreFooter: {
        primaryLabel: "",
        subtitle: "",
        outstanding: 0,
        current: 0,
        days1_30: 0,
        days31_60: 0,
        days60Plus: 0,
        risk: "low",
        isMoreFooter: true,
        moreCount: 174,
      },
    },
  },
  agent: {
    tabLabel: "Agent Outstanding",
    amountCr: 4.86,
    ageingBuckets: AGENT_BUCKETS,
    byBranch: {
      rows: AGENT_BRANCH_ROWS,
      total: {
        ...totalRow("Total Payables", AGENT_BRANCH_ROWS),
        risk: "low",
      },
    },
    byParty: {
      rows: [
        {
          primaryLabel: "Kuehne+Nagel",
          subtitle: "MUM · Net 30 · Ocean FCL",
          outstanding: 0.62,
          current: 0.48,
          days1_30: 0.1,
          days31_60: 0.04,
          days60Plus: 0,
          risk: "low",
        },
        {
          primaryLabel: "DB Schenker",
          subtitle: "MUM · Net 45 · Air",
          outstanding: 0.48,
          current: 0.36,
          days1_30: 0.08,
          days31_60: 0.04,
          days60Plus: 0,
          risk: "low",
        },
        {
          primaryLabel: "DHL Global",
          subtitle: "DEL · Net 30 · Air",
          outstanding: 0.42,
          current: 0.32,
          days1_30: 0.06,
          days31_60: 0.04,
          days60Plus: 0,
          risk: "low",
        },
      ],
      total: {
        primaryLabel: "Top agents",
        subtitle: "",
        outstanding: 4.86,
        current: 3.42,
        days1_30: 0.78,
        days31_60: 0.38,
        days60Plus: 0.28,
        risk: "low",
      },
      moreFooter: {
        primaryLabel: "",
        subtitle: "",
        outstanding: 0,
        current: 0,
        days1_30: 0,
        days31_60: 0,
        days60Plus: 0,
        risk: "low",
        isMoreFooter: true,
        moreCount: 35,
      },
    },
  },
  filterOptions: {
    branches: [
      { value: "mum", label: "Mumbai" },
      { value: "del", label: "Delhi" },
      { value: "blr", label: "Bangalore" },
    ],
    risks: [
      { value: "low", label: "Low" },
      { value: "medium", label: "Medium" },
      { value: "high", label: "High" },
    ],
  },
};
