import type { AccountsDashboardData } from "./accountsDashboardTypes";

/** Demo payload aligned with the Pentagon Finance profitability reference until the live API is wired. */
export const ACCOUNTS_DASHBOARD_MOCK: AccountsDashboardData = {
  meta: {
    title: "Profitability",
    subtitle: "CFO view · All branches",
    periodLabel: "Apr 2026 (MTD)",
    updatedAgo: "8 min ago",
    fyLabel: "FY 25–26",
  },
  kpis: [
    {
      key: "gross_revenue",
      label: "Gross Revenue",
      value: 38.42,
      unit: "Cr",
      showCurrency: true,
      trend: { direction: "up", text: "+9.6%", context: "vs. last period" },
      sparkline: [22, 20, 18, 15, 17, 12, 10, 8, 5],
      sparklineColor: "#16a34a",
    },
    {
      key: "direct_costs",
      label: "Direct Costs",
      value: 30.16,
      unit: "Cr",
      showCurrency: true,
      trend: { direction: "up", text: "+8.4%", context: "vs. last period" },
      sparkline: [22, 21, 18, 17, 16, 14, 12, 10, 8],
      sparklineColor: "#94a3b8",
    },
    {
      key: "gross_profit",
      label: "Gross Profit",
      value: 8.26,
      unit: "Cr",
      showCurrency: true,
      trend: { direction: "up", text: "+14.2%", context: "vs. last period" },
      sparkline: [24, 22, 20, 16, 15, 11, 8, 6, 4],
      sparklineColor: "#16a34a",
    },
    {
      key: "gp_margin",
      label: "GP Margin",
      value: 21.5,
      unit: "%",
      isPercent: true,
      trend: { direction: "up", text: "+0.9pp", context: "vs. last period" },
      sparkline: [20, 18, 16, 17, 14, 12, 10, 9, 7],
      sparklineColor: "#0ea5e9",
    },
    {
      key: "net_profit",
      label: "Net Profit",
      value: 3.84,
      unit: "Cr",
      showCurrency: true,
      trend: { direction: "up", text: "+18.7%", context: "vs. last period" },
      sparkline: [24, 22, 19, 18, 14, 12, 8, 6, 3],
      sparklineColor: "#16a34a",
    },
  ],
  breakdown: {
    dimensions: ["segment", "branch", "customer", "tradelane", "salesperson"],
    activeDimension: "segment",
    byDimension: {
      segment: {
        rows: [
          {
            name: "Ocean FCL",
            subtitle: "34% of mix · 412 jobs",
            revenue: 13.06,
            cost: 10.72,
            grossProfit: 2.34,
            marginPct: 17.9,
            marginTone: "warn",
            yoyPct: 11.4,
            yoyDirection: "up",
          },
          {
            name: "Air Freight",
            subtitle: "24% of mix · 286 AWBs",
            revenue: 9.22,
            cost: 6.75,
            grossProfit: 2.47,
            marginPct: 26.8,
            marginTone: "good",
            yoyPct: 14.8,
            yoyDirection: "up",
          },
          {
            name: "Ocean LCL",
            subtitle: "18% of mix · 528 CBM lots",
            revenue: 6.92,
            cost: 5.48,
            grossProfit: 1.44,
            marginPct: 20.8,
            marginTone: "neutral",
            yoyPct: 6.2,
            yoyDirection: "up",
          },
          {
            name: "Customs",
            subtitle: "12% of mix · 341 entries",
            revenue: 4.61,
            cost: 3.17,
            grossProfit: 1.44,
            marginPct: 31.2,
            marginTone: "good",
            yoyPct: 9.8,
            yoyDirection: "up",
          },
          {
            name: "Road",
            subtitle: "8% of mix · 198 trips",
            revenue: 3.07,
            cost: 2.69,
            grossProfit: 0.38,
            marginPct: 12.4,
            marginTone: "warn",
            yoyPct: -4.2,
            yoyDirection: "down",
          },
          {
            name: "Warehousing",
            subtitle: "4% of mix · 62 contracts",
            revenue: 1.54,
            cost: 1.12,
            grossProfit: 0.42,
            marginPct: 27.3,
            marginTone: "good",
            yoyPct: 3.1,
            yoyDirection: "up",
          },
        ],
        total: {
          name: "Total · all segments",
          subtitle: "6 segments · period",
          revenue: 38.42,
          cost: 30.16,
          grossProfit: 8.26,
          marginPct: 21.5,
          yoyPct: 11.2,
          yoyDirection: "up",
        },
      },
      branch: {
        rows: [
          {
            name: "Mumbai (MUM)",
            code: "MUM",
            branchVariant: "mum",
            subtitle: "HQ · Ocean + Air · 18 staff",
            revenue: 14.82,
            cost: 11.62,
            grossProfit: 3.2,
            marginPct: 21.6,
            marginTone: "neutral",
            yoyPct: 12.4,
            yoyDirection: "up",
          },
          {
            name: "Delhi (DEL)",
            code: "DEL",
            branchVariant: "del",
            subtitle: "North · Air freight · 12 staff",
            revenue: 9.24,
            cost: 7.71,
            grossProfit: 1.53,
            marginPct: 16.5,
            marginTone: "warn",
            yoyPct: -2.4,
            yoyDirection: "down",
          },
          {
            name: "Bangalore (BLR)",
            code: "BLR",
            branchVariant: "blr",
            subtitle: "South · Ocean LCL · 14 staff",
            revenue: 6.18,
            cost: 4.57,
            grossProfit: 1.61,
            marginPct: 26.1,
            marginTone: "good",
            yoyPct: 18.2,
            yoyDirection: "up",
          },
          {
            name: "Chennai (MAA)",
            code: "MAA",
            branchVariant: "maa",
            subtitle: "South · Ocean FCL · 11 staff",
            revenue: 4.42,
            cost: 3.47,
            grossProfit: 0.95,
            marginPct: 21.5,
            marginTone: "neutral",
            yoyPct: 8.6,
            yoyDirection: "up",
          },
          {
            name: "Kolkata (CCU)",
            code: "CCU",
            branchVariant: "ccu",
            subtitle: "East · Customs · 9 staff",
            revenue: 2.86,
            cost: 2.43,
            grossProfit: 0.43,
            marginPct: 15.0,
            marginTone: "warn",
            yoyPct: 4.1,
            yoyDirection: "up",
          },
          {
            name: "Ahmedabad (AMD)",
            code: "AMD",
            branchVariant: "amd",
            subtitle: "West · Road · 6 staff",
            revenue: 0.9,
            cost: 0.89,
            grossProfit: 0.01,
            marginPct: 1.5,
            marginTone: "bad",
            yoyLabel: "New",
            yoyPct: 0,
            yoyDirection: "down",
          },
        ],
        total: {
          name: "Total · all branches",
          subtitle: "6 branches · period",
          revenue: 38.42,
          cost: 30.16,
          grossProfit: 8.26,
          marginPct: 21.5,
          yoyPct: 11.2,
          yoyDirection: "up",
        },
      },
      customer: {
        rows: [
          {
            name: "Reliance Industries",
            subtitle: "MUM · 84 jobs · R. Sharma",
            revenue: 3.12,
            cost: 2.48,
            grossProfit: 0.64,
            marginPct: 20.5,
            marginTone: "neutral",
            yoyPct: 11.2,
            yoyDirection: "up",
          },
          {
            name: "Maruti Suzuki India",
            subtitle: "DEL · 62 jobs · P. Verma",
            revenue: 2.48,
            cost: 1.94,
            grossProfit: 0.54,
            marginPct: 21.8,
            marginTone: "neutral",
            yoyPct: 9.4,
            yoyDirection: "up",
          },
          {
            name: "Tata Steel",
            subtitle: "MUM · 48 jobs · R. Sharma",
            revenue: 2.14,
            cost: 1.72,
            grossProfit: 0.42,
            marginPct: 19.6,
            marginTone: "neutral",
            yoyPct: 6.8,
            yoyDirection: "up",
          },
          {
            name: "Wipro Ltd",
            subtitle: "BLR · 38 jobs · A. Nair",
            revenue: 1.86,
            cost: 1.38,
            grossProfit: 0.48,
            marginPct: 25.8,
            marginTone: "good",
            yoyPct: 14.2,
            yoyDirection: "up",
          },
          {
            name: "Infosys",
            subtitle: "BLR · 34 jobs · A. Nair",
            revenue: 1.62,
            cost: 1.28,
            grossProfit: 0.34,
            marginPct: 21.0,
            marginTone: "neutral",
            yoyPct: -1.8,
            yoyDirection: "down",
          },
          {
            name: "Havells India",
            subtitle: "DEL · 28 jobs · P. Verma",
            revenue: 1.42,
            cost: 1.18,
            grossProfit: 0.24,
            marginPct: 16.9,
            marginTone: "warn",
            yoyPct: 3.2,
            yoyDirection: "up",
          },
          {
            name: "Dabur India",
            subtitle: "DEL · 24 jobs · P. Verma",
            revenue: 1.18,
            cost: 0.96,
            grossProfit: 0.22,
            marginPct: 18.6,
            marginTone: "warn",
            yoyPct: 5.6,
            yoyDirection: "up",
          },
          {
            name: "L&T Construction",
            subtitle: "MAA · 22 jobs · S. Iyer",
            revenue: 1.04,
            cost: 0.82,
            grossProfit: 0.22,
            marginPct: 21.2,
            marginTone: "neutral",
            yoyPct: 7.4,
            yoyDirection: "up",
          },
          {
            name: "Adani Ports",
            subtitle: "MUM · 18 jobs · R. Sharma",
            revenue: 0.96,
            cost: 0.74,
            grossProfit: 0.22,
            marginPct: 22.9,
            marginTone: "neutral",
            yoyPct: 12.8,
            yoyDirection: "up",
          },
          {
            name: "Asian Paints",
            subtitle: "CCU · 16 jobs · M. Das",
            revenue: 0.8,
            cost: 0.68,
            grossProfit: 0.12,
            marginPct: 15.0,
            marginTone: "warn",
            yoyPct: 2.1,
            yoyDirection: "up",
          },
        ],
        total: {
          name: "Total · all customers",
          subtitle: "10 customers · period",
          revenue: 16.02,
          cost: 12.38,
          grossProfit: 3.64,
          marginPct: 22.7,
          yoyPct: 11.2,
          yoyDirection: "up",
        },
      },
      tradelane: {
        rows: [
          {
            name: "JNPT → Hamburg",
            subtitle: "Ocean FCL · 84 TEUs · weekly",
            revenue: 2.48,
            cost: 1.98,
            grossProfit: 0.5,
            marginPct: 20.2,
            marginTone: "neutral",
            yoyPct: 8.4,
            yoyDirection: "up",
          },
          {
            name: "Mundra → Rotterdam",
            subtitle: "Ocean FCL · 72 TEUs · weekly",
            revenue: 2.12,
            cost: 1.64,
            grossProfit: 0.48,
            marginPct: 22.6,
            marginTone: "neutral",
            yoyPct: 10.2,
            yoyDirection: "up",
          },
          {
            name: "Chennai → Singapore",
            subtitle: "Ocean LCL · 420 CBM · bi-weekly",
            revenue: 1.86,
            cost: 1.48,
            grossProfit: 0.38,
            marginPct: 20.4,
            marginTone: "neutral",
            yoyPct: 6.8,
            yoyDirection: "up",
          },
          {
            name: "Delhi → Frankfurt",
            subtitle: "Air Freight · 128 AWBs · daily",
            revenue: 1.74,
            cost: 1.22,
            grossProfit: 0.52,
            marginPct: 29.9,
            marginTone: "good",
            yoyPct: 14.6,
            yoyDirection: "up",
          },
          {
            name: "Mumbai → Dubai",
            subtitle: "Air Freight · 96 AWBs · daily",
            revenue: 1.52,
            cost: 1.14,
            grossProfit: 0.38,
            marginPct: 25.0,
            marginTone: "good",
            yoyPct: 11.8,
            yoyDirection: "up",
          },
          {
            name: "Kolkata → Chittagong",
            subtitle: "Ocean FCL · 48 TEUs · fortnightly",
            revenue: 1.28,
            cost: 1.08,
            grossProfit: 0.2,
            marginPct: 15.6,
            marginTone: "warn",
            yoyPct: -2.4,
            yoyDirection: "down",
          },
          {
            name: "Bangalore → Hong Kong",
            subtitle: "Air Freight · 64 AWBs · 3× weekly",
            revenue: 1.14,
            cost: 0.86,
            grossProfit: 0.28,
            marginPct: 24.6,
            marginTone: "good",
            yoyPct: 9.2,
            yoyDirection: "up",
          },
          {
            name: "Ahmedabad → Jebel Ali",
            subtitle: "Road · 42 trips · weekly",
            revenue: 0.92,
            cost: 0.82,
            grossProfit: 0.1,
            marginPct: 10.9,
            marginTone: "warn",
            yoyPct: 4.4,
            yoyDirection: "up",
          },
          {
            name: "Mumbai → Colombo",
            subtitle: "Ocean LCL · 280 CBM · weekly",
            revenue: 0.84,
            cost: 0.68,
            grossProfit: 0.16,
            marginPct: 19.0,
            marginTone: "neutral",
            yoyPct: 5.2,
            yoyDirection: "up",
          },
          {
            name: "Delhi → London",
            subtitle: "Air Freight · 52 AWBs · 2× weekly",
            revenue: 0.78,
            cost: 0.62,
            grossProfit: 0.16,
            marginPct: 20.5,
            marginTone: "neutral",
            yoyPct: 7.6,
            yoyDirection: "up",
          },
        ],
        total: {
          name: "Total · all tradelanes",
          subtitle: "10 tradelanes · period",
          revenue: 14.28,
          cost: 10.96,
          grossProfit: 3.32,
          marginPct: 23.2,
          yoyPct: 11.2,
          yoyDirection: "up",
        },
      },
      salesperson: {
        rows: [
          {
            name: "R. Sharma",
            subtitle: "MUM · Ocean lead · 14 customers",
            revenue: 4.82,
            cost: 3.6,
            grossProfit: 1.22,
            marginPct: 25.4,
            marginTone: "good",
            yoyPct: 14.2,
            yoyDirection: "up",
          },
          {
            name: "P. Verma",
            subtitle: "DEL · Air lead · 11 customers",
            revenue: 3.64,
            cost: 2.94,
            grossProfit: 0.7,
            marginPct: 19.2,
            marginTone: "neutral",
            yoyPct: 8.6,
            yoyDirection: "up",
          },
          {
            name: "A. Nair",
            subtitle: "BLR · Ocean LCL · 9 customers",
            revenue: 2.86,
            cost: 2.18,
            grossProfit: 0.68,
            marginPct: 23.8,
            marginTone: "neutral",
            yoyPct: 12.4,
            yoyDirection: "up",
          },
          {
            name: "S. Iyer",
            subtitle: "MAA · Ocean FCL · 8 customers",
            revenue: 2.42,
            cost: 1.92,
            grossProfit: 0.5,
            marginPct: 20.7,
            marginTone: "neutral",
            yoyPct: 6.2,
            yoyDirection: "up",
          },
          {
            name: "M. Das",
            subtitle: "CCU · Customs · 7 customers",
            revenue: 1.84,
            cost: 1.56,
            grossProfit: 0.28,
            marginPct: 15.2,
            marginTone: "warn",
            yoyPct: -1.4,
            yoyDirection: "down",
          },
          {
            name: "K. Patel",
            subtitle: "AMD · Road · 5 customers",
            revenue: 1.12,
            cost: 1.04,
            grossProfit: 0.08,
            marginPct: 7.1,
            marginTone: "bad",
            yoyLabel: "New",
            yoyPct: 0,
            yoyDirection: "down",
          },
          {
            name: "N. Reddy",
            subtitle: "BLR · Air freight · 6 customers",
            revenue: 2.18,
            cost: 1.62,
            grossProfit: 0.56,
            marginPct: 25.7,
            marginTone: "good",
            yoyPct: 16.8,
            yoyDirection: "up",
          },
          {
            name: "J. Singh",
            subtitle: "DEL · Multimodal · 8 customers",
            revenue: 2.54,
            cost: 2.08,
            grossProfit: 0.46,
            marginPct: 18.1,
            marginTone: "warn",
            yoyPct: 4.8,
            yoyDirection: "up",
          },
        ],
        total: {
          name: "Total · all salespersons",
          subtitle: "8 salespersons · period",
          revenue: 21.42,
          cost: 16.94,
          grossProfit: 4.48,
          marginPct: 20.9,
          yoyPct: 11.2,
          yoyDirection: "up",
        },
      },
    },
  },
  monthlyTrend: {
    fyLabel: "FY 25–26 · ₹ Cr",
    points: [
      { month: "Apr", revenue: 34.2, grossProfit: 7.1, marginPct: 20.8 },
      { month: "May", revenue: 35.8, grossProfit: 7.6, marginPct: 21.2 },
      { month: "Jun", revenue: 36.4, grossProfit: 7.8, marginPct: 21.4 },
      { month: "Jul", revenue: 37.9, grossProfit: 8.0, marginPct: 21.1 },
      { month: "Aug", revenue: 36.1, grossProfit: 7.5, marginPct: 20.8 },
      { month: "Sep", revenue: 38.6, grossProfit: 8.4, marginPct: 21.8 },
      { month: "Oct", revenue: 39.2, grossProfit: 8.5, marginPct: 21.7 },
      { month: "Nov", revenue: 40.1, grossProfit: 8.7, marginPct: 21.7 },
      { month: "Dec", revenue: 41.4, grossProfit: 9.0, marginPct: 21.7 },
      { month: "Jan", revenue: 39.8, grossProfit: 8.6, marginPct: 21.6 },
      { month: "Feb", revenue: 38.9, grossProfit: 8.3, marginPct: 21.3 },
      { month: "Mar", revenue: 38.4, grossProfit: 8.26, marginPct: 21.5 },
    ],
  },
  revenueMix: {
    total: 38.4,
    totalUnit: "Cr",
    items: [
      { name: "Ocean FCL", value: 13.06, pct: 34, color: "#0ea5e9" },
      { name: "Air Freight", value: 9.22, pct: 24, color: "#f59e0b" },
      { name: "Ocean LCL", value: 6.92, pct: 18, color: "#075985" },
      { name: "Customs", value: 4.61, pct: 12, color: "#ec4899" },
      { name: "Road", value: 3.07, pct: 8, color: "#64748b" },
      { name: "Warehousing", value: 1.54, pct: 4, color: "#6366f1" },
    ],
  },
  marginBySegment: {
    benchmarkPct: 21.5,
    items: [
      { name: "Customs", marginPct: 31.2, color: "#22c55e" },
      { name: "Air", marginPct: 26.8, color: "#22c55e" },
      { name: "Warehousing", marginPct: 27.3, color: "#22c55e" },
      { name: "Ocean LCL", marginPct: 20.8, color: "#0f2744" },
      { name: "Ocean FCL", marginPct: 17.9, color: "#0f2744" },
      { name: "Road", marginPct: 12.4, color: "#f59e0b" },
    ],
  },
};
