import type { BranchBudgetVsActualData } from "./branchBudgetVsActualTypes";

export const BRANCH_BUDGET_VS_ACTUAL_MOCK: BranchBudgetVsActualData = {
  meta: {
    title: "Branch Budget vs Actual",
    subtitle:
      "FY 25–26 YTD · ₹42.0 Cr revenue target · 91.5% achieved · GP target ₹9.20 Cr · 89.7% achieved",
    periodLabel: "FY 25–26 YTD",
    fyLabel: "FY 25–26",
  },
  kpis: [
    {
      label: "Budget YTD",
      value: 42.0,
      unit: "Cr",
      showCurrency: true,
      context: "Plan · revenue",
    },
    {
      label: "Actual YTD",
      value: 38.4,
      unit: "Cr",
      showCurrency: true,
      trendText: "−₹3.58 Cr",
      trendDirection: "down",
    },
    {
      label: "Achievement",
      value: 91.5,
      unit: "%",
      trendText: "−8.5pp vs plan",
      trendDirection: "down",
    },
    {
      label: "GP Achievement",
      value: 89.7,
      unit: "%",
      trendText: "₹95L below plan",
      trendDirection: "down",
    },
  ],
  branchPerformance: {
    rows: [
      {
        name: "Mumbai (MUM)",
        subtitle: "HQ · Ocean + Air · 18 staff",
        budget: 14.5,
        actual: 14.82,
        barActualWidthPct: 88,
        markerLeftPct: 86,
        barTone: "over",
        variance: 0.32,
        varianceDisplay: "+₹32 L",
        varianceDirection: "pos",
        achievementPct: 102,
      },
      {
        name: "Delhi (DEL)",
        subtitle: "North · Air freight · 12 staff",
        budget: 9.2,
        actual: 9.05,
        barActualWidthPct: 54,
        markerLeftPct: 55,
        barTone: "neutral",
        variance: -0.15,
        varianceDisplay: "−₹15 L",
        varianceDirection: "neg",
        achievementPct: 98,
      },
      {
        name: "Bangalore (BLR)",
        subtitle: "South · Air + Customs · 9 staff",
        budget: 6.8,
        actual: 6.52,
        barActualWidthPct: 39,
        markerLeftPct: 40,
        barTone: "neutral",
        variance: -0.28,
        varianceDisplay: "−₹28 L",
        varianceDirection: "neg",
        achievementPct: 96,
      },
      {
        name: "Chennai (MAA)",
        subtitle: "South · Ocean FCL · 10 staff",
        budget: 6.2,
        actual: 5.18,
        barActualWidthPct: 31,
        markerLeftPct: 37,
        barTone: "under",
        variance: -1.02,
        varianceDisplay: "−₹1.02 Cr",
        varianceDirection: "neg",
        achievementPct: 84,
      },
      {
        name: "Ahmedabad (AMD)",
        subtitle: "West · Ocean + Road · 7 staff",
        budget: 3.2,
        actual: 2.18,
        barActualWidthPct: 13,
        markerLeftPct: 19,
        barTone: "under",
        variance: -1.02,
        varianceDisplay: "−₹1.02 Cr",
        varianceDirection: "neg",
        achievementPct: 68,
      },
      {
        name: "Kolkata (CCU)",
        subtitle: "East · New territory · 5 staff",
        watchLabel: "Watch",
        budget: 2.1,
        actual: 0.67,
        barActualWidthPct: 4,
        markerLeftPct: 13,
        barTone: "under",
        variance: -1.43,
        varianceDisplay: "−₹1.43 Cr",
        varianceDirection: "neg",
        achievementPct: 32,
      },
    ],
    total: {
      name: "All Branches",
      budget: 42.0,
      actual: 38.42,
      barActualWidthPct: 53,
      markerLeftPct: 58,
      barTone: "neutral",
      variance: -3.58,
      varianceDisplay: "−₹3.58 Cr",
      varianceDirection: "neg",
      achievementPct: 91.5,
    },
  },
  monthlyRunRate: {
    fyLabel: "FY 25–26 · ₹ Cr · all branches",
    points: [
      { month: "Apr", budget: 3.2, actual: 2.9 },
      { month: "May", budget: 3.4, actual: 3.1 },
      { month: "Jun", budget: 3.5, actual: 3.2 },
      { month: "Jul", budget: 3.7, actual: 3.4 },
      { month: "Aug", budget: 3.8, actual: 3.5 },
      { month: "Sep", budget: 4.0, actual: 3.8 },
      { month: "Oct", budget: 4.2, actual: 4.0 },
      { month: "Nov", budget: 4.4, actual: 4.2 },
      { month: "Dec", budget: 4.6, actual: 4.4 },
      { month: "Jan", budget: 4.8, actual: 4.6 },
      { month: "Feb", budget: 4.9, actual: 4.5 },
      { month: "Mar", budget: 5.0, actual: 4.2, isForecast: true },
    ],
  },
  byMode: {
    items: [
      { name: "Ocean FCL", actual: 13.1, budget: 12.6, barWidthPct: 75, targetLeftPct: 72, tone: "neutral" },
      { name: "Air", actual: 9.2, budget: 8.4, barWidthPct: 68, targetLeftPct: 62, tone: "good" },
      { name: "Ocean LCL", actual: 6.9, budget: 7.8, barWidthPct: 48, targetLeftPct: 55, tone: "warn" },
      { name: "Customs", actual: 4.6, budget: 4.0, barWidthPct: 38, targetLeftPct: 32, tone: "good" },
      { name: "Road", actual: 3.1, budget: 4.2, barWidthPct: 21, targetLeftPct: 30, tone: "warn" },
      { name: "Warehousing", actual: 1.5, budget: 2.0, barWidthPct: 12, targetLeftPct: 17, tone: "warn" },
    ],
  },
  varianceCallouts: [
    {
      amount: "−₹1.43 Cr",
      tone: "bad",
      text: "Kolkata branch ramp-up slower than plan — 32% achievement",
    },
    {
      amount: "−₹1.02 Cr",
      tone: "bad",
      text: "Chennai losing Ocean FCL volume to MUM consolidation",
    },
    {
      amount: "+₹78 L",
      tone: "good",
      text: "Air freight beat plan on Delhi-led EU lanes",
    },
    {
      amount: "+₹62 L",
      tone: "good",
      text: "Customs growing 18% YoY at MUM & BLR",
    },
  ],
};
